"""add policy fields

Revision ID: 619333d92715
Revises: h7f8g9h0i1j2
Create Date: 2026-05-02 11:41:06.199552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '619333d92715'
down_revision: Union[str, Sequence[str], None] = 'h7f8g9h0i1j2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('policy_accepted', sa.Boolean(), server_default='false', nullable=False), schema='db_schema')
    op.add_column('users', sa.Column('policy_accepted_at', sa.DateTime(timezone=True), nullable=True), schema='db_schema')
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at', schema='db_schema')
    op.drop_column('users', 'policy_accepted_at', schema='db_schema')
    op.drop_column('users', 'policy_accepted', schema='db_schema')
    # ### end Alembic commands ###
